name: glife
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
    
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  intl: ^0.19.0
  image_picker: ^1.1.1
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  health: ^10.2.0
  fl_chart: ^0.68.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1

fonts:
  - family: CustomFont
    fonts:
      - asset: assets/fonts/CustomFont-Regular.ttf

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_driver:
    sdk: flutter
  test:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^4.0.0
  


flutter:
  uses-material-design: true
  assets: 
    - assets/images/logo.jpeg
    - assets/images/character.jpeg
    - assets/images/sunglasses.jpg
    - assets/images/character_sunglasses.png
    - assets/images/character_sunglasses.jpeg
    - assets/images/c2.jpg
    - assets/images/hat.jpg
    - assets/images/testchest.jpg
    - assets/images/helmet.jpg